[server]
host = "0.0.0.0"
port = 3000
output = "output"
script_path = "sh"
static_path = "./public"
user_data_path = "./user_data.bin"

[database]
driver = "sqlite"
dsn = "db/logs.db"

[json_paths]
server_list = "db/serverlist.json"
last_server = "db/lastserver.json"
server_info = "db/serverinfo.json"

[ftp]
host = "192.168.200.20" # 外网
# host = "192.168.200.21"                # 内网
port = "21"
user = "username"
password = "password"
# apk_path = "/DQ1-c/out"
# zip_path = "/DQ1-c/CLIENT_DQ1_DQDQ_CN"
apk_path = "/-=共享你想共享的=-/dqtemp"
zip_path = "/-=共享你想共享的=-/dqtemp"
log_dir = "output/logs/ftp"      # 添加 FTP 上传日志目录配置
max_log_size = 20971520          # 20MB in bytes
