[server]
host = "0.0.0.0"
port = 3000
output = "../publish/output"
script_path = "sh"
user_data_path = "./user_data.bin"

# 静态路径配置改为数组
static_paths = [
    { route = "/static", path = "./public" },
    { route = "/uploads", path = "./uploads" },
    { route = "/cdn", path = "./cdn" },
]

[database]
driver = "sqlite"
dsn = "db/logs.db"

[json_paths]
server_list = "db/serverlist.json"
last_server = "db/lastserver.json"
server_info = "db/serverinfo.json"
notice_list = "db/noticelist.json"
notice_num = "db/noticenum.json"

[ftp]
host = "192.168.200.20"
port = "21"
user = "TestDQ"
password = "135ajdq"
# apk_path = "/DQ1-c/out"
# zip_path = "/DQ1-c/CLIENT_DQ1_DQDQ_CN"
apk_path = "/PublisherDQ2"
zip_path = "/PublisherDQ2"
log_dir = "output/logs/ftp"
max_log_size = 20971520

[auth]
jwt_secret = "your-secret-key-here"
token_expire = 86400                # 24小时
