[server]
host = "0.0.0.0"
port = 3000
output = "output"
script_path = "sh"
static_path = "./public"
user_data_path = "./user_data.bin"

[modules]
logs = true       # 日志模块
stats = true      # 统计模块
browse = true     # 文件浏览模块
ftp = true        # FTP上传模块
serverconf = true # 服务器配置模块
cmd = true        # 命令模块
pack = true       # 打包模块

[database]
driver = "sqlite"
dsn = "db/logs.db"

[json_paths]
server_list = "db/serverlist.json"
last_server = "db/lastserver.json"
server_info = "db/serverinfo.json"

[ftp]
host = "192.168.200.20"
port = "21"
user = "123456"
password = "000000"
# apk_path = "/DQ1/out"
# zip_path = "/DQ1/CLIENT_DQ1_DQDQ_CN"
apk_path = "/-=共享你想共享的=-/dqtemp"
zip_path = "/-=共享你想共享的=-/dqtemp"
log_dir = "output/logs/ftp"
max_log_size = 20971520
