# 应用配置
[app]
is_dev = true     # 是否为开发环境
is_secure = false # 是否启用安全模式（HTTPS）

# 服务器配置
[server]
host = "0.0.0.0"
port = 3000
output = "../publish/output"
script_path = "sh"
user_data_path = "./user_data.bin"

# 静态路径配置改为数组
static_paths = [
    { route = "/static", path = "./public" },
    { route = "/uploads", path = "./uploads" },
    { route = "/cdn", path = "./cdn" },
]

[database]
driver = "sqlite"
dsn = "data/unitool.db"
max_open_conns = 100     # 最大打开连接数
max_idle_conns = 10      # 最大空闲连接数
conn_max_lifetime = 3600 # 连接最大生命周期（秒）

[json_paths]
server_list = "data/serverlist.json"
last_server = "data/lastserver.json"
server_info = "data/serverinfo.json"
notice_list = "data/noticelist.json"
notice_num = "data/noticenum.json"

[ftp]
host = "192.168.200.20"
port = "21"
user = "TestDQ"
password = "135ajdq"
# apk_path = "/DQ1-c/out"
# zip_path = "/DQ1-c/CLIENT_DQ1_DQDQ_CN"
apk_path = "/PublisherDQ2"
zip_path = "/PublisherDQ2"
log_dir = "output/logs/ftp"
max_log_size = 20971520

[auth]
jwt_secret = "your-secret-key"
token_expire = 259200          # 72小时
