basePath: /api/v1
definitions:
  models.StatsRecord:
    properties:
      app_id:
        type: integer
      created_at:
        type: integer
      device_name:
        type: string
      graphics_divice:
        type: string
      graphics_mem:
        type: integer
      id:
        type: integer
      login_id:
        type: integer
      mtime:
        type: integer
      package_name:
        type: string
      product_name:
        type: string
      role_name:
        type: string
      system_cpu:
        type: string
      system_mem:
        type: integer
    type: object
host: localhost:3000
info:
  contact:
    email: huayicai@gamil.com
    name: API Support
    url: https://github.com/andycai/unitool
  description: Unity游戏开发辅助工具API文档
  license:
    name: MIT
    url: https://github.com/andycai/goapi/blob/main/LICENSE
  termsOfService: http://swagger.io/terms/
  title: UnityTool API
  version: "1.0"
paths:
  /api/stats:
    get:
      consumes:
        - application/json
      description: 获取分页统计记录列表
      parameters:
        - default: 1
          description: 页码
          in: query
          name: page
          type: integer
        - default: 20
          description: 每页数量
          in: query
          name: pageSize
          type: integer
        - description: 搜索关键词
          in: query
          name: search
          type: string
        - description: "过滤日期 (格式: YYYY-MM-DD)"
          in: query
          name: date
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: 包含统计列表和分页信息
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 获取统计列表
      tags:
        - stats
    post:
      consumes:
        - application/json
      description: 创建新的统计记录，支持图片上传（base64编码）
      parameters:
        - description: 统计记录数据
          in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/models.StatsRecord"
      produces:
        - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: "#/definitions/models.StatsRecord"
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 创建统计记录（含图片）
      tags:
        - stats
  /api/stats/{id}:
    delete:
      consumes:
        - application/json
      description: 根据ID删除统计记录及其关联数据
      parameters:
        - description: 统计记录ID
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 删除单个统计
      tags:
        - stats
  /api/stats/before:
    delete:
      consumes:
        - application/json
      description: 删除指定日期前的所有统计记录
      parameters:
        - description: "删除截止日期 (格式: YYYY-MM-DD)"
          in: query
          name: date
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 删除历史统计
      tags:
        - stats
  /api/stats/details:
    get:
      consumes:
        - application/json
      description: 根据登录ID获取详细统计信息
      parameters:
        - description: 用户登录ID
          in: query
          name: login_id
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 获取统计详情
      tags:
        - stats
swagger: "2.0"
