basePath: /api/v1
definitions:
  stats.StatsResponse:
    properties:
      app_id:
        type: string
      created_at:
        type: string
      device_name:
        type: string
      graphics_gpu:
        type: string
      graphics_mem:
        type: number
      id:
        type: integer
      login_id:
        type: string
      package_name:
        type: string
      role_name:
        type: string
      system_cpu:
        type: string
      system_mem:
        type: number
    type: object
host: localhost:3000
info:
  contact:
    email: your-email@example.com
    name: API Support
    url: https://github.com/andycai/unitool
  description: Unity游戏开发辅助工具API文档
  license:
    name: MIT
    url: https://github.com/andycai/unitool/blob/main/LICENSE
  termsOfService: http://swagger.io/terms/
  title: UnityTool API
  version: "1.0"
paths:
  /api/v1/stats:
    get:
      consumes:
      - application/json
      description: 获取游戏性能统计数据列表
      parameters:
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 10
        description: 每页数量
        in: query
        name: limit
        type: integer
      - description: 搜索关键词
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/stats.StatsResponse'
            type: array
      summary: 获取统计数据列表
      tags:
      - stats
  /api/v1/stats/{id}:
    delete:
      consumes:
      - application/json
      description: 删除指定的统计数据
      parameters:
      - description: 统计数据ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 删除统计数据
      tags:
      - stats
    get:
      consumes:
      - application/json
      description: 获取单条游戏性能统计数据详情
      parameters:
      - description: 统计数据ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/stats.StatsResponse'
      summary: 获取统计数据详情
      tags:
      - stats
swagger: "2.0"
